### ISSUE TITLE
Голосовые уведомления

### ISSUE THREAD

**Issue by ChelovekMurga** [morfeusys/dusiassistant#1]
Я считаю, что было бы удобнее, если бы по дефолту можно было выбирать от каких приложений ты хочешь получать уведомления, а не наоборот.

**Comment by morfeusys** [comment]
Давайте обсуждать.
Пользователь первый раз включает уведомления. Он ничего не хочет СЕЙЧАС настраивать, он просто хочет протестить функцию. Ему приходит уведомление - и он его слышит. 
Далее приходит уведомление от другого приложения, и он понимает, что не хочет его слышать. ТОГДА он идет в настройки и меняет поведение.
Я исхожу из такой логики пользователя.

**Comment by ChelovekMurga** [comment]
Ну, это больше относится не к багам, а к предиркам или пожеланиям. Просто написал как мне кажется удобным.

**Comment by Vladimir070381** [comment]
а как настроить отдельные уведомления для приложений?(и он понимает, что не хочет его слышать. ТОГДА он идет в настройки и меняет поведение. )

**Comment by morfeusys** [comment]
Что такое "настроить отдельные уведомления для приложений"? Вы можете просто исключить какие-то приложения, чтобы их уведомления не озвучивались. В настройках уведомлений в Дусе.

**Comment by Vladimir070381** [comment]
не могу найти( Вы можете просто исключить какие-то приложения, чтобы их уведомления не озвучивались.) у меня либо все,либо ни чего??????

**Comment by morfeusys** [comment]
Зайдите в настройки Уведомления и там есть Черный список

**Comment by ChelovekMurga** [comment]
Сложно найти именно то, что нужно дабавить в ЧС. Например когда я начинаю писать, Дуся говорит "Новое уведомление от платформы андроид. Выбор клавиатуры fleksy". Пробовал добавить в ЧС клавиатуру, но это не то.

**Comment by Vladimir070381** [comment]
где этот черный список?ни могу найти!

**Comment by morfeusys** [comment]
Ну там где вы включали уведомления. В том же окне. Настройки - голосовые уведомления - черный список

**Comment by ChelovekMurga** [comment]
Настройки - голосовые уведомления - черный список.

**Comment by Vladimir070381** [comment]
нет у меня такого!!!!!!

**Comment by morfeusys** [comment]
Относительно платформы андроид - исправим.
Насчет черного списка - пришлите скриншот

**Comment by Vladimir070381** [comment]
на мыло отправил

**Comment by morfeusys** [comment]
Зачем на мыло? И тут есть возможность. Внизу есть ссылочка "Attach files by dragging & dropping,  Choose Files selecting them, or pasting from the clipboard."

Относительно вашего скрина - вы сперва активируйте функцию уведомлений. Кнопочку жмакните.

**Comment by Vladimir070381** [comment]
активирую и вот так
![screenshot_2015-11-16-16-56-28 1](https://cloud.githubusercontent.com/assets/15859399/11183494/fe81e486-8c82-11e5-95fc-cd6d18f99b52.png)

**Comment by morfeusys** [comment]
Ну да - потом идите в настройки уведомлений. И там должны появиться настройки.

**Comment by Vladimir070381** [comment]
потом иду в настройки и там первый скрин я уже присылал

**Comment by morfeusys** [comment]
А какая у вас версия андроида?

**Comment by Vladimir070381** [comment]
![screenshot_2015-11-16-17-44-09 1](https://cloud.githubusercontent.com/assets/15859399/11184557/72b89916-8c89-11e5-9d2a-83755f5ab016.png)

**Comment by morfeusys** [comment]
Интересно...

**Comment by Vladimir070381** [comment]
актиирую галочку-выхожу!захожу-настройки-голос уведом-и нет ни кокого списка!правильный путь?

**Comment by morfeusys** [comment]
Хм, странно, но видимо сервис уведомлений в Дусе почему-то не активируется системой..
Я сделаю в обновлении, чтобы настройки были видны всегда.

**Comment by Vladimir070381** [comment]
ок

**Comment by morfeusys** [comment]
Сделаю белый список в обновлении вдобавок к черному

**Comment by Vladimir070381** [comment]
мне хотябы черный пока
