### ISSUE TITLE
Не уведомляет при входящем звонке

### ISSUE THREAD

**Issue by ChelovekMurga** [morfeusys/dusiassistant#10]
Играет мелодия звонка, затихает на какое-то время и снова играет. Ни имени, ни номера не озвучивает.

**Comment by morfeusys** [comment]
Включена опция "Озвучивать входящий звонок" в настройках функции "Звонки"?
Включена ли опция "Только при гарнитуре"? Подключена ли гарнитура при этом?

**Comment by ChelovekMurga** [comment]
Первая опция включена. только при гарнитуре.

**Comment by morfeusys** [comment]
Не понял. Какие галочки включены точно? Подключена ли гарнитура? Какая гарнитура - проводная или беспроводная?

**Comment by ChelovekMurga** [comment]
Стоит галочка на только при включенной гарнитуре. Гарнитура у меня проводная.

**Comment by ChelovekMurga** [comment]
Заработало само собой.
