### ISSUE TITLE
Нельзя редактировать фразы в списке фраз

### ISSUE THREAD

**Issue by ChelovekMurga** [morfeusys/dusiassistant#11]
Скрипты - действия - сказать. Здесь нельзя редактировать фразы, только удалить.

**Comment by morfeusys** [comment]
Вам это сильно мешает?

**Comment by ChelovekMurga** [comment]
Когда написал большую фразу, а потом понял, что запятые тоже озвучиваются или нашел одну ошибку, то приходится удалять и писать все заново.

**Comment by morfeusys** [comment]
Хорошо, исправляем.

**Comment by ChelovekMurga** [comment]
спасибо.

**Comment by ChelovekMurga** [comment]
Вот такие ситуации я имел ввиду :) 
![screenshot_2015-11-18-02-11-55](https://cloud.githubusercontent.com/assets/15857743/11222548/4044c524-8d95-11e5-8e78-32a2a3ba0a80.jpg)

**Comment by morfeusys** [comment]
Исправлено в alpha-3
