### ISSUE TITLE
Не запускается музыка в ВК на смарте

### ISSUE THREAD

**Issue by ChelovekMurga** [morfeusys/dusiassistant#12]
Немного не в тему наверное, но у меня не работает скрипт "Музыка ВКонтакте" которым поделился Смелый Дима. Выполнил все условия из описания, но дуся вроде пытается что-то сделать, но ничего не включает, просто тишина.

**Comment by morfeusys** [comment]
Установили Katemobile по той ссылке, которая в описании скрипта? Залогинились ли в Katemobile?
Эта функция пока тестовая, так как Katemobile пока не выпустил обновление.
Также может быть у вас ранее не установился скрипт - так как была с этим бага.

**Comment by ChelovekMurga** [comment]
Kate установило с 4pda. Ссылку в описании не заметил. Когда первый раз установил этот скрипт - в нем небыло "действий". На второй раз они появились. 
Сейчас скачаю Катю по ссылке и попробую заново.

**Comment by ChelovekMurga** [comment]
Работает. Спасибо. Просто ссылка была неактивна.
