### ISSUE TITLE
Вылет при повороте экрана в настройках функций

### ISSUE THREAD

**Issue by nick2ld** [morfeusys/dusiassistant#13]
Если зайти в функции звонки, сообщения, Навигация и в телефоне включен авто поворот экрана, перевернуть экран - происходит вылет с ошибкой

**Comment by ChelovekMurga** [comment]
Тоже самое.

**Comment by morfeusys** [comment]
Пожалуйста, пишите заголовок баги чуть информативнее

**Comment by morfeusys** [comment]
Исправлено в alpha-2
