### ISSUE TITLE
Не включает громкую связь

### ISSUE THREAD

**Issue by nick2ld** [morfeusys/dusiassistant#14]

**Comment by morfeusys** [comment]
Старый баг, еще с прошлых версиях. Программное включение громкой связи не на всех аппаратах работает.

**Comment by nick2ld** [comment]
и? исправлять бум? это же альфа?

**Comment by morfeusys** [comment]
Если будет найдено решение, то будем, если нет - то нет

**Comment by morfeusys** [comment]
Исправлено в 1.5.0-beta
