### ISSUE TITLE
Не дожидается ответа пользователя.

### ISSUE THREAD

**Issue by Tramfh** [morfeusys/dusiassistant#18]
Хотел написать "Не дожидается ответа при второй, третьей попытке узнать на какой именно номер слать смс", но оказывается рандомно срабатывает глюк. Сразу после вопроса Дуси, следует сигнал начала прослушивания, далее следуют почти одновременно звук окончания прослушивания и фраза "вас не слышно".

**Comment by morfeusys** [comment]
Это не глюк программы, это у вас не работает голосовой поиск нормально. Это не относится к функции смс нарямую

**Comment by Tramfh** [comment]
Ну кстати логично, понял, спасибо
