### ISSUE TITLE
Крэш при обновлении

### ISSUE THREAD

**Issue by Yauheni-Harbatouski** [morfeusys/dusiassistant#20]
при обновлении версии поверх старой приложение часто крашится, приходится удалять старую версию и устанавливать новую

**Comment by morfeusys** [comment]
Что такое "часто крашится"? Как "часто" вы обновляете альфа версию, которая всего лишь пока одна?

**Comment by Yauheni-Harbatouski** [comment]
Было 1 обновление со старой версии на альфу, и альфа 1 раз обновилась.
Решил написать этот баг, потому что приложение вылетало при любых действиях.
16 Ноя 2015 г. 18:39 пользователь "Dmitry Che" notifications@github.com
написал:

**Comment by morfeusys** [comment]
Проверим

**Comment by morfeusys** [comment]
При обновлении все было нормально. А у вас?

**Comment by Yauheni-Harbatouski** [comment]
Теперь не вылетает, все отлично и длинные скрипты нормально проматывает без вылетов
