### ISSUE TITLE
НЕ запускается аудиоплеер

### ISSUE THREAD

**Issue by Vladimir070381** [morfeusys/dusiassistant#22]
захожу список функций-приложения-плеер по умолчанию-выбираю _аудиоплеер_,говорю открой плеер и вот что происходит
![screenshot_2015-11-16-19-13-43 1](https://cloud.githubusercontent.com/assets/15859399/11187190/8683efb0-8c96-11e5-8536-eaf39902f594.png)

**Comment by morfeusys** [comment]
Что происходит? Падает какая-то программа. Какой именно плеер?

**Comment by Vladimir070381** [comment]
верхний падает аудиоплеер 
![screenshot_2015-11-16-19-42-26 1](https://cloud.githubusercontent.com/assets/15859399/11188008/e6bc4dac-8c99-11e5-8e3c-48ff02703a3d.png)

**Comment by morfeusys** [comment]
Ну это уж его дело.. Дуся ему сигнал на открытие послала, а он падает.

**Comment by Vladimir070381** [comment]
ПОНЯЛ СПАСИБО
