### ISSUE TITLE
вверху в уведомлениях пропал микрофон и надписи то,что я прошу сделать Дусю!в шторке микрофон остался!

### ISSUE THREAD

**Issue by Vladimir070381** [morfeusys/dusiassistant#23]

**Comment by morfeusys** [comment]
Это не баг. Это изменение, которое так и задумывалось.
У вас больше не висит значок, но при этом быстрый старт доступен.
Если вам нужно видеть, что распозналось - используйте интерфейс

**Comment by Vladimir070381** [comment]
А ХОТЬ ставь галочку хоть нет,изменений нет!я вот про что!

**Comment by morfeusys** [comment]
А, вы про галочку. Ну так бы и писали. Оформляйте сообщение о баги корректнее.
Хотя где вы там нашли галочку? Вроде уж убрана из настроек.

**Comment by Vladimir070381** [comment]
настройки-фон режим-открывать интерфейс!у меня так:-)

**Comment by Vladimir070381** [comment]
Ну так бы и писали. Оформляйте сообщение о баги корректнее._я не упрекаю ни кого,а пишу как работает на моем устройстве!я не профи поэтому строго не судите!_

**Comment by Vladimir070381** [comment]
после обновы ни че не поменялось

**Comment by morfeusys** [comment]
Открывать интерфейс - что вы тут увидели общего с уведомлением и микрофоном? ))
Эта опция для того, чтобы открывался интерфейс Дуси при активации любым способом. В том числе и при нажатии на Дуся старт. Ничего общего с микрофоном в статус баре здесь нет.
