### ISSUE TITLE
Ошибка на Android 6 при отсутствии прав

### ISSUE THREAD

**Issue by barei001** [morfeusys/dusiassistant#24]
Андроид 6.0,нексус5.При запуске пишет,"В приложении,произошла ошибка" и крашится.

**Comment by barei001** [comment]
Запустилось,только после того, как в настройках телефона, в приложениях,дал разрешение Дусе отправлять,смс,и доступ ко всему прочему.

**Comment by morfeusys** [comment]
А у вас там нужно вручную права выдавать?

**Comment by barei001** [comment]
Ну,автоматом он почему-то не запрашивает.

**Comment by morfeusys** [comment]
Мда, от версии к версии у гугла проблемы с головой только усиливаются...

**Comment by morfeusys** [comment]
Исправлено в alpha-5
