### ISSUE TITLE
Озвучивает уведомления по 2 раза

### ISSUE THREAD

**Issue by ChelovekMurga** [morfeusys/dusiassistant#25]
Собственно озвучивает уведомления по 2 раза. Стоит галочка на гарнитуре и стоит галочка на этом приложении в белом списке.

**Comment by Vladimir070381** [comment]
где блин у Вас эти черные и белые списки??????

**Comment by morfeusys** [comment]
Обновитесь. Теперь и черные и белые списки доступны всегда в настрйоках уведомлений.

**Comment by Vladimir070381** [comment]
обновился с утра и ни че не появилось,я уже проверял

**Comment by morfeusys** [comment]
Хорошо, буду смотреть

**Comment by ChelovekMurga** [comment]
Теперь озвучивает как надо, один раз.

**Comment by Vladimir070381** [comment]
черные и белые списки ЗАРАБОТАЛИ!!!спасибо
