### ISSUE TITLE
Поворот экрана 

### ISSUE THREAD

**Issue by EvgeniyShatalov** [morfeusys/dusiassistant#29]
Не работает поворот экрана на планшете. Android 4.2

**Comment by morfeusys** [comment]
Где именно не работает? Пишите сообщения чуть подробнее.

**Comment by EvgeniyShatalov** [comment]
Когда в режиме ландшафт нажимаешь "Быстрый старт" Экран поворачивает я в портретный режим.

**Comment by morfeusys** [comment]
Вы имеете в виду что открывается интерфейс с микрофоном в портретном режиме? Да, он пока работает только в портретном режиме.

**Comment by EvgeniyShatalov** [comment]
Да
