### ISSUE TITLE
Настройки уведомлений теряются после перезагрузки

### ISSUE THREAD

**Issue by ChelovekMurga** [morfeusys/dusiassistant#3]
Когда Дуся вылетает по тем или иным причинам, то в большинстве случаев (может и всегда) слетают все настройки. То же самое при перезагрузки телефона.

**Comment by morfeusys** [comment]
Все настройки - это какие? Вообще все?
Я протестировал так - поставил какие-то галочки в меню "Фоновый режим", перезагрузил телефон, зашел в настройки "Фоновый режим" - все ОК.

**Comment by ChelovekMurga** [comment]
В черном списке голосовых уведомлений пропадают галочки.

**Comment by morfeusys** [comment]
Не могу повторить.. У вас воспроизводится каждый раз после перезагрузки?

**Comment by ChelovekMurga** [comment]
Сейчас попробовал перезагрузить телефон и спровоцировал вылет Дуси. Галочки в этот раз не слетели. Но до этого раза 3-4 они слетали.

**Comment by morfeusys** [comment]
Интересно. Буду пытаться повторить. Если у кого-то еще такое обнаружится - сообщите.

**Comment by ChelovekMurga** [comment]
Ах да. По мимо галочек в уведомлениях слетала авторизация в ВК

**Comment by morfeusys** [comment]
Не могу повторить пока...

**Comment by morfeusys** [comment]
Все еще теряются?

**Comment by ChelovekMurga** [comment]
Нет.

**Comment by ChelovekMurga** [comment]
Думал, что давно ответил.
