### ISSUE TITLE
Не полностью видно текст описания опубликованного скрипта в описании 

### ISSUE THREAD

**Issue by ChelovekMurga** [morfeusys/dusiassistant#32]
Не полностью видно текст описания опубликованного скрипта в описании в горизонтальном положении 
![screenshot_2015-11-18-02-55-50](https://cloud.githubusercontent.com/assets/15857743/11223045/03f747b0-8d98-11e5-9d22-908971e3b4e4.jpg)

**Comment by morfeusys** [comment]
Текст ограничен в этой области, так что это ошибка модерирования
