### ISSUE TITLE
при написании названия скрипта выключается HTC управление на клавиатуре

### ISSUE THREAD

**Issue by morfeusys** [morfeusys/dusiassistant#39]

**Comment by ChelovekMurga** [comment]
при написании названия скрипта выключается авто исправление на клавиатуре.

**Comment by Zoom22** [comment]
Подтверждаю есть такое неудобство

**Comment by morfeusys** [comment]
А в чем неудобство?

**Comment by Zoom22** [comment]
Установлена клавиатура swiftkey, которая выводит автоматические подсказки, позволяет автозавершать ввод слов. Во всех других полях ввода они работают

**Comment by morfeusys** [comment]
А, "ВЫключается"! Заголовок баги написан неправильно. Будьте внимательнее.

**Comment by morfeusys** [comment]
Исправлено в alpha-5
