### ISSUE TITLE
При редактировании параметров RSS-рассылки вместо обновления рассылки добавляется новая

### ISSUE THREAD

**Issue by Zoom22** [morfeusys/dusiassistant#41]
Нажимаем на существующую RSS-рассылку, вносим изменения, жмем ОК (кстати нет кнопки отмена). Остается и старая рассылка, и добавляется новая. 
Еще пожелания по RSS-рассылкам:
1. Можно сделать паузу после (перед?) чтением каждой записи? Сейчас получается словесная каша, читает без остановок всё подряд.
2. Можно указывать в самой рассылке сколько заголовков читать? А то на одних ресурсах по 100 новостей, на других 1-2. Еще лучше, при наличии технической возможности, указывать период за который прочитать записи.

**Comment by morfeusys** [comment]
Исправлено в alpha-5
Пауза добавлена. Улучшение настройки самих рассылок быть может позже.
