### ISSUE TITLE
При отправке сообщения в сообщество google+, Дуся уведомляет об этом два раза. 

### ISSUE THREAD

**Issue by ChelovekMurga** [morfeusys/dusiassistant#42]
Да и оповещение отправки сообщения в google+ думаю вообще не нужно. Отдельно его отключить нельзя.

**Comment by morfeusys** [comment]
Ну тут как бы техническое ограничение есть - Дуся не знает, что это за оповещение. На отправку, на прием или какое-то еще. Она знает только, что это оповещение и от какого приложения.
