### ISSUE TITLE
Не редактируются/не удаляются параметры в интенте

### ISSUE THREAD

**Issue by Zoom22** [morfeusys/dusiassistant#44]
Собственно сабж. 
Пытаюсь разобраться с интентами. Помогите с примером  действия-intent на запуск дефолтного приложения карт (гугл или яндекс) в точке, определённой предыдущей командой Дуся "где я нахожусь". 
Ставлю target activity,  действие ru.yandex.yandexmaps.action.SHOW_POINT_ON_MAP, package ru.yandex.yandexmaps,  параметры lat= $place_lat, lon= $place_lat, z=12.
В итоге открываются я.карты, но не в точке с нужными координатами.

**Comment by morfeusys** [comment]
Почему не удаляются? Долгое нажатие - удалить. 
Насчёт самого интента - вы сделали ошибку в параметре lon. Он должен иметь значение $place_lon. А у вас $place_lat

**Comment by morfeusys** [comment]
Кстати теперь не обязательно выяснять где я чтобы получить координаты. Теперь они доступны без всякой команды в стандартных переменных loc_lat и loc_lon. Это если вам нужны только координаты.

**Comment by morfeusys** [comment]
Исправлено в alpha-5
