### ISSUE TITLE
Поиск скриптов и передача ссылки на скрипт

### ISSUE THREAD

**Issue by ChelovekMurga** [morfeusys/dusiassistant#5]
Хотелось бы, что бы была возможность искать скрипт через поиск (ведь их там скоро станет много) и/или возможность делиться ссылкой на скрипт.

**Comment by morfeusys** [comment]
Обязательно. Позже, в релизной версии. Делиться ссылками тоже можно будет.

**Comment by Vladimir070381** [comment]
скрипт _брать ли с собой зонт_ показывает на экране погоду,но ни чего не говорит!!!!!

**Comment by ChelovekMurga** [comment]
Тоже

**Comment by morfeusys** [comment]
Да, ошибка в процессинге скриптов с "тихим" выполнением

**Comment by morfeusys** [comment]
В alpha-6 реализован поиск скриптов

**Comment by Vladimir070381** [comment]
+
