### ISSUE TITLE
При создании нового контакта, сохраняет ФИО с маленькой буквы

### ISSUE THREAD

**Issue by Tramfh** [morfeusys/dusiassistant#50]
еще вопрос должна ли дуся уметь отдельно добавлять новый номер старому контакту? потому что вроде как начинает это делать(команда "добавь номер контакту"), успешно выбирает контакт и не спрашивает собственно номер или я цепляюсь за что то другое?

**Comment by morfeusys** [comment]
Пока нет, но сделаем

**Comment by morfeusys** [comment]
Исправлено в alpha-8
