### ISSUE TITLE
Тихий режим

### ISSUE THREAD

**Issue by EvgeniyShatalov** [morfeusys/dusiassistant#54]
Возможно ли добавить функцию ночного режима, который наступал бы по времени или по команде. Если возможно то чтобы в нем присутствовал белый список программ и контактов. P. S.  Если не туда написал пожелание то заранее извиняюсь.

**Comment by morfeusys** [comment]
Не совсем понятно, что такое "тихий режим"? В каком плане "тихий"? Вы не написали про саму функциональность.

**Comment by EvgeniyShatalov** [comment]
Когда нужно чтобы не звонил телефон. Но важные звонки приходили. Ставить кучу сторонних программ не хочется. А это сказал "Совещание" или "Ночь" и она отключили все лишнее.

**Comment by EvgeniyShatalov** [comment]
Просто не все программы поддерживают интернет, а через танкер сложно править разные правила.

**Comment by morfeusys** [comment]
Не совсем понятно, что такое "важные звонки"? По поводу тихого режима - вы и сейчас можете сделать скрипт, который при слове Ночь будет выключать звук звонка, а при слове Привет будет включать его обратно.

**Comment by EvgeniyShatalov** [comment]
Важный звонок например родители, дети, жена. На эти телефонные звонки я всегда отвечаю, хоть в 3 часа ночи.

**Comment by morfeusys** [comment]
Тут уж Дуся не поможет. Это ей нужно заводить списки, следить кто звонит. Как-то изменять громкость во время звонка и изменять обратно потом.

**Comment by EvgeniyShatalov** [comment]
Дуся ведь может озвучивать имя входящего контакта, значит она может по идее сверить его со списком. Если контакт из списка то включить громкость.

**Comment by morfeusys** [comment]
Это может работать очень нестабильно. Нужно много тестов. Пока откладываем.
