### ISSUE TITLE
Стали криво работать скрипты

### ISSUE THREAD

**Issue by ChelovekMurga** [morfeusys/dusiassistant#56]
При срабатывании шаблона, говорит "открываю аутентификатор" и зачем-то предлагает контакт из телефонной книги. Таких скриптов несколько. ![screenshot_2015-12-09-16-37-26](https://cloud.githubusercontent.com/assets/15857743/11681748/0e925404-9e8b-11e5-8bfa-b58c2ebda04a.jpg)
![screenshot_2015-12-09-16-37-33](https://cloud.githubusercontent.com/assets/15857743/11681749/10554d46-9e8b-11e5-9265-061ec6ed0b6b.jpg)
![screenshot_2015-12-09-16-40-59](https://cloud.githubusercontent.com/assets/15857743/11681783/46f769e2-9e8b-11e5-8524-e167c44b4e92.jpg)

**Comment by morfeusys** [comment]
Это не криво работающие скрипты, а команда поиска контактов такая. В обновлении она будет другой. Так что к скриптам данный баг не имеет отношения.
Кстати вопрос. Зачем вам скрипт чтобы открыть приложение? Недостаточно синонима?

**Comment by ChelovekMurga** [comment]
Озвучка открытия приложения не очень красиво звучала.
