### ISSUE TITLE
Пропала строка. 

### ISSUE THREAD

**Issue by EvgeniyShatalov** [morfeusys/dusiassistant#58]
Пропала строка в "настройки -> голосовые уведомления" "не позже". Пробовал ставить с нуля эффекта нет. 
https://drive.google.com/file/d/0B1I7PEWn2k1GZWFLekFuZFU1RnM/view?usp=docslist_api

**Comment by EvgeniyShatalov** [comment]
Немного не хватает
https://drive.google.com/file/d/0B1I7PEWn2k1GUU1Ga0dQRlNvMVU/view?usp=docslist_api

**Comment by morfeusys** [comment]
Починили

**Comment by EvgeniyShatalov** [comment]
Не совсем до конца.  При листании вниз появляется белая область внизу экрана. В других пунктах меню этого нет. 
https://drive.google.com/file/d/0B1I7PEWn2k1GdE5UZkZDS1RwaGc/view?usp=docslist_api
