### ISSUE TITLE
Активация через Окей Google не работает при включенных уведомлениях

### ISSUE THREAD

**Issue by nick2ld** [morfeusys/dusiassistant#6]
Итак. При включеных: Открывать интерфейс, Быстрый старт, Использовать гарнитуру, Голосовые уведомления. - Сказав окей гугл - начинается тарабарщина - несколько раз повторяется - "Новое сообщение от приложения гугл" - после чего интерфейс виснет, дуся вылетает.

**Comment by morfeusys** [comment]
Понятно, причина в уведомлениях. Исправлем.

**Comment by ChelovekMurga** [comment]
У меня уведомления выключены. Дуся не перехватывает запросы Google now. Все дела по инструкции как на видео.

**Comment by morfeusys** [comment]
Проверьте что включена служба доступности Ассистент Дуся. Андроид вырубает ее после обновлений и еще по ему известным причинам.

**Comment by ChelovekMurga** [comment]
В специальных возможна чтя еще раз отключил и включил Дусю и все заработало.

**Comment by nick2ld** [comment]
у меня нет (

**Comment by morfeusys** [comment]
Исправлено в alpha-2
