### ISSUE TITLE
Банер о пробном периоде появляется даже если есть покупка

### ISSUE THREAD

**Issue by nick2ld** [morfeusys/dusiassistant#7]
При клике "Перейти в google play" - ошибка - Невозможно соединиться с Google Play
При клике "У меня уже есть полная версия" - ничего не происходит.

**Comment by morfeusys** [comment]
Так у вас уже есть полная версия или нет?
У вас стоит лакипатчер или фридом на устройстве?

Кстати ошибка восстановления покупки была еще в самой первой альфа версии. Попробуйте зайти в Google Play и обновить Дусю.

**Comment by nick2ld** [comment]
лакипатчер или фридом на устройстве - не стоит.
дуся куплена - давно. )

**Comment by morfeusys** [comment]
Попробуйте удалить и поставить заново. Может быть у вас как-то встала старая версия с багом, который не восстанавливал покупку. Либо альфа-версия почему-то конфликтует с вашим аккаунтом.

**Comment by nick2ld** [comment]
Так вверху на оранжевом фоне написано - ПОЛНАЯ версия, но кнопки с предложением покупки не пропадают... и слишком крупный шрифт - полная версия.

**Comment by morfeusys** [comment]
Я так понимаю, что после запуска вам выводится баннер о пробном периоде?? При этом вам доступна функция Уведомления?
Если да - то значит покупка восстановилась, но проблема в баннере. Попробуйте просто закрыть приложение по back и еще раз открыть. 
В любом случае, покупка восстановилась автоматически.

**Comment by nick2ld** [comment]
закрывал... баннер вводит в заблуждение...

**Comment by morfeusys** [comment]
Банер починим.

**Comment by morfeusys** [comment]
Исправлено в alpha-2
