### ISSUE TITLE
Как активировать дусю на часах голосом?

### ISSUE THREAD

**Issue by nick2ld** [morfeusys/dusiassistant#9]
Ок гугл не работает

**Comment by morfeusys** [comment]
Голосом Дусю на часах активировать пока невозможно технически. Только свайпом из верхнего левого угла вправо.
Либо голосом активировать Окей гугл, сказать "запусти Дусю", а потом уж командовать Дусе. Но это если сильно хочется.

**Comment by nick2ld** [comment]
После вывода ответа на часах - можно добавить действия по клику на карточку и свайпы с действиями, а то режима диалога не получается?!

**Comment by morfeusys** [comment]
Свайп вниз - будут действия если они доступны. Свайп еще раз из левого угла вправо - включается микрофон.

**Comment by nick2ld** [comment]
А можно просто тап по карточке? А то получается - как тебя зовут? - Дуся. И нужно елозить по экрану... не удобно. И срабатывает через раз. + у меня интерактивный циферблат, т.е. к кликам можно привязывать отдельные приложения - дусю хочу туда прикрутить.
Вот циферблат - https://play.google.com/store/apps/details?id=com.stmp.minimalface

**Comment by morfeusys** [comment]
Понятно. Хорошо, тап по карточке будет активировать микрофон.
